// frontend/src/components/ProductoForm.vue
<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import api from '../services/api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import {
  Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle,
} from '@/components/ui/dialog'
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from '@/components/ui/select'

const props = defineProps<{
  producto: any | null
}>()

const emit = defineEmits<{
  save: [data: any]
  cancel: []
}>()

const open = ref(true)

const form = ref({
  titulo: '',
  descripcion: '',
  precio: 0,
  stock: 0,
  isbn: '',
  anio_publicacion: 2024,
  imagen_url: '',
  categoria_id: '',
  editorial_id: '',
  autores: [] as number[],
})

const categorias = ref<any[]>([])
const editoriales = ref<any[]>([])
const autores = ref<any[]>([])
const errors = ref<string[]>([])

onMounted(async () => {
  const [catRes, edRes, autRes] = await Promise.all([
    api.get('/categorias'),
    api.get('/editoriales'),
    api.get('/autores'),
  ])
  categorias.value = catRes.data
  editoriales.value = edRes.data
  autores.value = autRes.data
})

watch(() => props.producto, (p) => {
  if (p) {
    form.value = {
      titulo: p.titulo ?? '',
      descripcion: p.descripcion ?? '',
      precio: p.precio ?? 0,
      stock: p.stock ?? 0,
      isbn: p.isbn ?? '',
      anio_publicacion: p.anio_publicacion ?? 2024,
      imagen_url: p.imagen_url ?? '',
      categoria_id: String(p.categoria_id ?? ''),
      editorial_id: String(p.editorial_id ?? ''),
      autores: [],
    }
  }
}, { immediate: true })

function validate(): boolean {
  errors.value = []
  if (!form.value.titulo.trim()) errors.value.push('Titulo es requerido')
  if (form.value.precio <= 0) errors.value.push('Precio debe ser mayor a 0')
  if (form.value.stock < 0) errors.value.push('Stock no puede ser negativo')
  if (!form.value.categoria_id) errors.value.push('Categoria es requerida')
  if (!form.value.editorial_id) errors.value.push('Editorial es requerida')
  return errors.value.length === 0
}

function submit() {
  if (!validate()) return
  emit('save', {
    ...form.value,
    categoria_id: Number(form.value.categoria_id),
    editorial_id: Number(form.value.editorial_id),
  })
}

function handleOpenChange(val: boolean) {
  if (!val) emit('cancel')
  open.value = val
}
</script>

<template>
  <Dialog :open="open" @update:open="handleOpenChange">
    <DialogContent class="sm:max-w-lg max-h-[90vh] overflow-y-auto">
      <DialogHeader>
        <DialogTitle>{{ producto?.id_producto ? 'Editar' : 'Nuevo' }} Producto</DialogTitle>
      </DialogHeader>

      <div v-if="errors.length" class="rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive space-y-1">
        <div v-for="e in errors" :key="e">{{ e }}</div>
      </div>

      <form @submit.prevent="submit" class="space-y-4">
        <div class="grid grid-cols-2 gap-4">
          <div class="space-y-2">
            <Label>Titulo *</Label>
            <Input v-model="form.titulo" required />
          </div>
          <div class="space-y-2">
            <Label>ISBN</Label>
            <Input v-model="form.isbn" />
          </div>
        </div>

        <div class="space-y-2">
          <Label>Descripcion</Label>
          <Textarea v-model="form.descripcion" rows="2" />
        </div>

        <div class="grid grid-cols-3 gap-4">
          <div class="space-y-2">
            <Label>Precio *</Label>
            <Input v-model.number="form.precio" type="number" step="0.01" min="0.01" required />
          </div>
          <div class="space-y-2">
            <Label>Stock *</Label>
            <Input v-model.number="form.stock" type="number" min="0" required />
          </div>
          <div class="space-y-2">
            <Label>Anio</Label>
            <Input v-model.number="form.anio_publicacion" type="number" />
          </div>
        </div>

        <div class="grid grid-cols-2 gap-4">
          <div class="space-y-2">
            <Label>Categoria *</Label>
            <Select v-model="form.categoria_id">
              <SelectTrigger>
                <SelectValue placeholder="Seleccionar..." />
              </SelectTrigger>
              <SelectContent>
                <SelectItem v-for="c in categorias" :key="c.id_categoria" :value="String(c.id_categoria)">
                  {{ c.nombre }} ({{ c.tipo }})
                </SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div class="space-y-2">
            <Label>Editorial *</Label>
            <Select v-model="form.editorial_id">
              <SelectTrigger>
                <SelectValue placeholder="Seleccionar..." />
              </SelectTrigger>
              <SelectContent>
                <SelectItem v-for="e in editoriales" :key="e.id_editorial" :value="String(e.id_editorial)">
                  {{ e.nombre }}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        <div class="space-y-2">
          <Label>Autores</Label>
          <select v-model="form.autores" multiple class="w-full h-20 rounded-md border border-input bg-background px-3 py-1 text-sm transition-colors duration-200 focus:border-primary focus:ring-2 focus:ring-primary/20 focus:outline-none">
            <option v-for="a in autores" :key="a.id_autor" :value="a.id_autor">
              {{ a.nombre }}
            </option>
          </select>
        </div>

        <div class="space-y-2">
          <Label>Imagen (URL)</Label>
          <Input v-model="form.imagen_url" placeholder="https://covers.openlibrary.org/b/isbn/..." />
          <img v-if="form.imagen_url" :src="form.imagen_url" class="mt-2 h-24 w-24 object-cover rounded-md border" />
        </div>

        <DialogFooter>
          <Button type="button" variant="outline" class="transition-all duration-200 hover:bg-muted" @click="emit('cancel')">Cancelar</Button>
          <Button type="submit" class="transition-all duration-200 hover:scale-105 hover:shadow-md">Guardar</Button>
        </DialogFooter>
      </form>
    </DialogContent>
  </Dialog>
</template>

// frontend/src/components/ProductoForm.tsx
import { useState, useEffect, useCallback } from 'react'
import api from '@/services/api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'

interface Props { producto: any | null; onSave: (data: any) => void; onCancel: () => void }

export default function ProductoForm({ producto, onSave, onCancel }: Props) {
  const [form, setForm] = useState({ titulo: '', isbn: '', precio: '', stock: '', anio_publicacion: '', descripcion: '', imagen_url: '', id_categoria: '', id_editorial: '', autores: '' as string })
  const [categorias, setCategorias] = useState<any[]>([])
  const [editoriales, setEditoriales] = useState<any[]>([])
  const [autoresList, setAutoresList] = useState<any[]>([])
  const [errors, setErrors] = useState<string[]>([])

  useEffect(() => {
    api.get('/categorias').then(r => setCategorias(r.data)).catch(() => {})
    api.get('/editoriales').then(r => setEditoriales(r.data)).catch(() => {})
    api.get('/autores').then(r => setAutoresList(r.data)).catch(() => {})
  }, [])

  useEffect(() => {
    if (producto) {
      setForm({
        titulo: producto.titulo ?? '', isbn: producto.isbn ?? '', precio: String(producto.precio ?? ''), stock: String(producto.stock ?? ''),
        anio_publicacion: String(producto.anio_publicacion ?? ''), descripcion: producto.descripcion ?? '', imagen_url: producto.imagen_url ?? '',
        id_categoria: String(producto.id_categoria ?? ''), id_editorial: String(producto.id_editorial ?? ''), autores: String(producto.autor_ids ?? ''),
      })
    }
  }, [producto])

  const validate = useCallback(() => {
    const errs: string[] = []
    if (!form.titulo.trim()) errs.push('Titulo requerido')
    if (!form.precio || Number(form.precio) <= 0) errs.push('Precio debe ser > 0')
    if (form.stock !== '' && Number(form.stock) < 0) errs.push('Stock debe ser >= 0')
    return errs
  }, [form])

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    const errs = validate(); setErrors(errs); if (errs.length) return
    const data: any = { titulo: form.titulo, isbn: form.isbn || null, precio: Number(form.precio), stock: Number(form.stock) || 0, anio_publicacion: form.anio_publicacion ? Number(form.anio_publicacion) : null, descripcion: form.descripcion || null, imagen_url: form.imagen_url || null }
    if (form.id_categoria) data.id_categoria = Number(form.id_categoria)
    if (form.id_editorial) data.id_editorial = Number(form.id_editorial)
    if (form.autores) data.autores = form.autores.split(',').map(Number).filter(Boolean)
    onSave(data)
  }

  const set = (f: string) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm(p => ({ ...p, [f]: e.target.value }))

  return (
    <Dialog open onOpenChange={(v) => { if (!v) onCancel() }}>
      <DialogContent className="sm:max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader><DialogTitle>{producto ? 'Editar' : 'Nuevo'} Producto</DialogTitle></DialogHeader>
        {errors.length > 0 && <div className="rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive space-y-1">{errors.map(e => <p key={e}>{e}</p>)}</div>}
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2"><Label>Titulo *</Label><Input value={form.titulo} onChange={set('titulo')} /></div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2"><Label>ISBN</Label><Input value={form.isbn} onChange={set('isbn')} /></div>
            <div className="space-y-2"><Label>Año</Label><Input type="number" value={form.anio_publicacion} onChange={set('anio_publicacion')} /></div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2"><Label>Precio *</Label><Input type="number" step="0.01" value={form.precio} onChange={set('precio')} /></div>
            <div className="space-y-2"><Label>Stock</Label><Input type="number" value={form.stock} onChange={set('stock')} /></div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2"><Label>Categoria</Label>
              <Select value={form.id_categoria} onValueChange={v => setForm(p => ({ ...p, id_categoria: v }))}>
                <SelectTrigger><SelectValue placeholder="Seleccionar" /></SelectTrigger>
                <SelectContent>{categorias.map(c => <SelectItem key={c.id_categoria} value={String(c.id_categoria)}>{c.tipo} - {c.nombre}</SelectItem>)}</SelectContent>
              </Select>
            </div>
            <div className="space-y-2"><Label>Editorial</Label>
              <Select value={form.id_editorial} onValueChange={v => setForm(p => ({ ...p, id_editorial: v }))}>
                <SelectTrigger><SelectValue placeholder="Seleccionar" /></SelectTrigger>
                <SelectContent>{editoriales.map(e => <SelectItem key={e.id_editorial} value={String(e.id_editorial)}>{e.nombre}</SelectItem>)}</SelectContent>
              </Select>
            </div>
          </div>
          <div className="space-y-2"><Label>Autores (IDs separados por coma)</Label><Input value={form.autores} onChange={set('autores')} placeholder="1,2,3" /><p className="text-xs text-muted-foreground">Disponibles: {autoresList.map(a => `${a.id_autor}:${a.nombre}`).join(', ')}</p></div>
          <div className="space-y-2"><Label>URL Imagen</Label><Input value={form.imagen_url} onChange={set('imagen_url')} placeholder="https://..." /></div>
          <div className="space-y-2"><Label>Descripcion</Label><Textarea value={form.descripcion} onChange={set('descripcion')} rows={3} /></div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={onCancel}>Cancelar</Button>
            <Button type="submit">Guardar</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
